# Generated by Django 4.0.3 on 2022-04-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='troop_id',
            field=models.IntegerField(unique=True),
        ),
    ]
