# Generated by Django 4.0.3 on 2022-04-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.IntegerField()),
                ('troops', models.ManyToManyField(to='troops.troop')),
            ],
        ),
    ]
