# Generated by Django 4.0.3 on 2022-04-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troops', '0002_alter_troop_troop_id'),
        ('lots', '0002_alter_lots_lot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='troops',
            field=models.ManyToManyField(null=True, to='troops.troop'),
        ),
    ]
