# Generated by Django 4.0.3 on 2022-04-05 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caravana', models.IntegerField(null=True)),
                ('rfid', models.IntegerField(null=True)),
                ('troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troops.troop')),
            ],
        ),
    ]
